### ISSUE TITLE
The source code of queue-tick is only 2 lines of code.

### ISSUE THREAD

**Issue by Raynos** [vweevers/catering#5]
```
~/optoolco/tmp1234
$ cat node_modules/queue-tick/
LICENSE               process-next-tick.js  README.md             
package.json          queue-microtask.js    test.js               
raynos at raynos-Precision-5530  
~/optoolco/tmp1234
$ cat node_modules/queue-tick/queue-microtask.js 
module.exports = typeof queueMicrotask === 'function' ? queueMicrotask : (fn) => Promise.resolve().then(fn)
raynos at raynos-Precision-5530  
~/optoolco/tmp1234
$ cat node_modules/queue-tick/process-next-tick.js 
module.exports = process.nextTick.bind(process)
```

Can you remove this dependency that contains literally only two lines of JavaScript.

**Comment by vweevers** [comment]
PR is welcome. I don't have a strong opinion about 2 lines of code. Originally my intent was to use `queue-tick` in more modules (which would have a benefit because then not every module has to explain this code) but that didn't happen

**Comment by Raynos** [comment]
I added a pull request for ( https://github.com/vweevers/catering/pull/6 ).

The motivation is to reduce the number of transitive dependencies of `leveldown`. Because `leveldown` is effectively a native dependency I need to include it in my binaries seperately from the rest of the code that's bundled via `esbuild`

This means I'm maintaining a whitelist

```js
depsToCopy.push(
      'leveldown',
      'abstract-leveldown',
      'buffer',
      'base64-js',
      'ieee754',
      'is-buffer',
      'level-concat-iterator',
      'level-supports',
      'queue-microtask',
      'napi-macros',
      'node-gyp-build',
      'catering',
      'queue-tick'
    )
```

I recent update to leveldown / abstract-leveldown grew this list with two new dependencies, `catering` & `queue-tick`.
